In [2]:
import pandas as pd
import numpy as np
import plotly.graph_objs as go
import plotly.tools as tls
from plotly.offline import iplot, init_notebook_mode
from plotly.subplots import make_subplots
import cufflinks
from plotly import tools
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("CH4_CO_health_effect_NEW.csv")
print(df.head())

   CH4  CO2  CO     Health Effect
0  2.1  213   3  No Health Effect
1  2.1  293   2  No Health Effect
2  2.1  268   5  No Health Effect
3  2.0  275   6  No Health Effect
4  2.0  341   1  No Health Effect


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9065 entries, 0 to 9064
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   CH4            9065 non-null   float64
 1   CO2            9065 non-null   int64  
 2   CO             9065 non-null   int64  
 3   Health Effect  9065 non-null   object 
dtypes: float64(1), int64(2), object(1)
memory usage: 283.4+ KB


In [5]:
df.isnull().sum().values.sum()

0

In [6]:
df.nunique()

CH4                51
CO2              7375
CO               4824
Health Effect      12
dtype: int64

In [7]:
df.head()

CH4  CO2  CO     Health Effect
0  2.1  213   3  No Health Effect
1  2.1  293   2  No Health Effect
2  2.1  268   5  No Health Effect
3  2.0  275   6  No Health Effect
4  2.0  341   1  No Health Effect

In [8]:
metric_col = ["Health Effect"]

In [9]:
features = ['CH4','CO2','CO']

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.metrics import roc_auc_score,roc_curve,scorer
from sklearn.metrics import f1_score
import statsmodels.api as sm
from sklearn.metrics import precision_score,recall_score
from yellowbrick.classifier import DiscriminationThreshold

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning:

The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning:

The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.



In [14]:
X = np.array(df[features])
y = np.array(df['Health Effect'])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [16]:
unique, counts = np.unique(y, return_counts=True)
dict(zip(unique, counts))

{'Death within 1-3 minutes of exposure.': 266,
 'Death within 30 minutes.': 1562,
 'Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.': 159,
 'Headache and nausea after 1-2 hours of exposure.\nLife threatening in 3 hours.': 458,
 'Headache, nausea, and dizziness after 20 minutes of exposure.\nDeath within 1-2 hours.': 1427,
 'Headache, nausea, and dizziness after 45 minutes; collapse and unconsciousness after 1 hour of exposure.\nDeath within 2-3 hours.': 207,
 'Headache, nausea, and dizziness after 5-10 minutes; collapse and unconsciousness after 30 minutes of exposure.\nDeath within 1 hour.': 1743,
 'Immediate physiological effects, unconsciousness.\nDeath within 1-3 minutes of exposure.': 206,
 'Loss of consciousness after 1 hour of exposure.': 515,
 'No Health Effect': 979,
 'Possible health effects with long-term exposure.': 1477,
 'Slight headache after 1-2 hours.': 66}

In [17]:
#LOGISTIC REGRESSION

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
logit= LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,penalty='l2', random_state=None, solver='liblinear', tol=0.0001,verbose=0, warm_start=False)
logit.fit(X_train, y_train)
y_pred = logit.predict(X_test)

In [60]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred))
f=open("healthi_logit.txt", "w")
f.write(metrics.classification_report(y_test, y_pred))
print("Accuracy   Score : ", accuracy_score(y_test, y_pred))
f.close()

                                                                                                                                     precision    recall  f1-score   support

                                                                                              Death within 1-3 minutes of exposure.       0.23      1.00      0.38        60
                                                                                                           Death within 30 minutes.       0.97      0.60      0.74       279
                                                                  Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.       0.04      0.62      0.07        26
                                                      Headache and nausea after 1-2 hours of exposure.
Life threatening in 3 hours.       0.00      0.00      0.00        92
                                              Headache, nausea, and dizziness after 20 minutes of exposure.
Death within 1-2 hours.   

In [61]:
print (logit.summary())

AttributeError: 'LogisticRegression' object has no attribute 'summary'

In [22]:
#confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[ 60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 266,   0,   0,   0,   0,  13,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  26,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  92,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 185,   0, 102,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  50,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  15,   0, 327,   0,   0,   0,   0,   0],
       [  0,  30,   0,   0,   0,   0,   7,  10,   0,   0,   0,   0],
       [  0,   0,   0,   0, 101,   0,   6,   0,   1,   0,   0,   0],
       [  0,   0,   0,   0, 141,   0,   0,   0,   0,   0,  51,   0],
       [  0,   0,   0,   0, 281,   0,   0,   0,   0,   0,  32,   0],
       [  0,   0,   0,   0,  17,   0,   0,   0,   0,   0,   0,   0]],
      dtype=int64)

In [23]:
coefficients  = pd.DataFrame(logit.coef_.ravel())
column_df     = pd.DataFrame(features)
coef_sumry    = (pd.merge(coefficients,column_df,left_index= True,
                          right_index= True, how = "left"))
coef_sumry.columns = ["coefficients","features"]
coef_sumry    = coef_sumry.sort_values(by = "coefficients",ascending = False)

In [24]:
# #plot coeffs
# trace4 = go.Bar(x = coef_sumry["features"],y = coef_sumry["coefficients"],
#                 name = "coefficients",
#                 marker = dict(color = coef_sumry["coefficients"],
#                               colorscale = "Picnic",
#                               line = dict(width = .6,color = "black")))

# layout = go.Layout(dict(title = "Feature Importances",
#                         autosize = False,
#                         height  = 720,
#                         width   = 800,
#                         margin = dict(b = 195),
#                         yaxis   = dict(tickfont = dict(size = 9)),
#                         xaxis   = dict(tickfont = dict(size = 9)),
#                         plot_bgcolor = 'rgba(240,240,240, 0.95)',
#                         paper_bgcolor = 'rgba(240,240,240, 0.95)',
#                        )
#                   )
# # fig['layout'].update(showlegend=False, title="Feature Importances" ,
# #                          autosize = True,
# #                          plot_bgcolor = 'rgba(240,240,240, 0.95)',
# #                          paper_bgcolor = 'rgba(240,240,240, 0.95)',
# #                          margin = dict(b = 195))
# fig["layout"]["xaxis"].update(dict(showgrid = True,tickfont = dict(size = 10),
#                                         tickangle = 90))

# #defining figure and plotting
# fig = go.Figure(trace4,layout=layout)
# iplot(fig)

In [25]:

logit.coef_

array([[ 3.43252569e-01, -1.08230095e-04,  2.16214424e-05],
       [-9.48624173e-01,  1.00393296e-05,  6.46702805e-06],
       [-8.55118742e-01, -7.91275999e-07, -1.90625043e-03],
       [-9.85472281e-04, -6.42008406e-04,  5.06396194e-04],
       [-1.82479244e-04, -3.47472374e-06, -3.33296914e-04],
       [-1.06913558e+00,  4.74271297e-06, -7.72883954e-04],
       [-7.74343639e-01, -7.09552252e-05,  1.17630472e-03],
       [-3.36381171e+00, -1.48290716e-06,  8.06233185e-04],
       [-5.73699806e-04, -7.82643382e-04,  1.28902215e-03],
       [ 1.14362283e-04, -1.71911947e-03, -7.70403535e-04],
       [ 1.44321914e-04,  6.14835916e-05, -8.94300881e-03],
       [-1.29597662e+00, -2.10186128e-04, -1.42211905e-03]])

In [26]:
from imblearn.over_sampling import SMOTE
#resampling need to be done on training dataset only
X_train_res, y_train_res = SMOTE().fit_sample(X_train, y_train)

In [27]:
logit= LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,penalty='l2', random_state=None, solver='liblinear', tol=0.0001,verbose=0, warm_start=False)
logit.fit(X_train_res, y_train_res)
y_pred = logit.predict(X_test)

In [28]:
print(metrics.classification_report(y_test, y_pred))

                                                                                                                                     precision    recall  f1-score   support

                                                                                              Death within 1-3 minutes of exposure.       0.23      1.00      0.38        60
                                                                                                           Death within 30 minutes.       0.97      0.60      0.74       279
                                                                  Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.       0.04      0.62      0.07        26
                                                      Headache and nausea after 1-2 hours of exposure.
Life threatening in 3 hours.       0.00      0.00      0.00        92
                                              Headache, nausea, and dizziness after 20 minutes of exposure.
Death within 1-2 hours.   

C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [29]:
print(accuracy_score(y_test, y_pred))

0.46442360728075016


In [30]:
#Stochastic Gradient Classifier
from sklearn.linear_model import SGDClassifier
sg = SGDClassifier(random_state=42)
sg.fit(X_train_res,y_train_res)
pred = sg.predict(X_test)
from sklearn.metrics import classification_report,accuracy_score
print(classification_report(y_test, pred))
print(accuracy_score(y_test, pred))

                                                                                                                                     precision    recall  f1-score   support

                                                                                              Death within 1-3 minutes of exposure.       0.14      1.00      0.24        60
                                                                                                           Death within 30 minutes.       0.30      0.89      0.44       279
                                                                  Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.       0.00      0.00      0.00        26
                                                      Headache and nausea after 1-2 hours of exposure.
Life threatening in 3 hours.       0.00      0.00      0.00        92
                                              Headache, nausea, and dizziness after 20 minutes of exposure.
Death within 1-2 hours.   

C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [31]:
print(accuracy_score(y_test, pred))

0.16933259790402647


In [32]:
#Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train_res,y_train_res) 
dtree_predictions = dtree_model.predict(X_test)
print(classification_report(y_test, dtree_predictions))
print(accuracy_score(y_test, dtree_predictions))

                                                                                                                                     precision    recall  f1-score   support

                                                                                              Death within 1-3 minutes of exposure.       0.05      1.00      0.09        60
                                                                                                           Death within 30 minutes.       0.00      0.00      0.00       279
                                                                  Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.       0.00      0.00      0.00        26
                                                      Headache and nausea after 1-2 hours of exposure.
Life threatening in 3 hours.       0.00      0.00      0.00        92
                                              Headache, nausea, and dizziness after 20 minutes of exposure.
Death within 1-2 hours.   

C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [33]:
print(accuracy_score(y_test, dtree_predictions))

0.3116381687810259


In [34]:
#SVM
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'poly', C = 1).fit(X_train_res,y_train_res) 
svm_predictions = svm_model_linear.predict(X_test)
print(classification_report(y_test, svm_predictions))
print(accuracy_score(y_test, svm_predictions))

                                                                                                                                     precision    recall  f1-score   support

                                                                                              Death within 1-3 minutes of exposure.       0.76      1.00      0.86        60
                                                                                                           Death within 30 minutes.       0.96      0.82      0.88       279
                                                                  Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.       0.03      0.23      0.05        26
                                                      Headache and nausea after 1-2 hours of exposure.
Life threatening in 3 hours.       0.48      0.46      0.47        92
                                              Headache, nausea, and dizziness after 20 minutes of exposure.
Death within 1-2 hours.   

In [35]:
print(accuracy_score(y_test, svm_predictions))

0.39437396580253725


In [36]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train_res,y_train_res) 
knn_predictions = knn.predict(X_test) 
print(classification_report(y_test, knn_predictions))
print(accuracy_score(y_test, knn_predictions))

                                                                                                                                     precision    recall  f1-score   support

                                                                                              Death within 1-3 minutes of exposure.       0.97      1.00      0.98        60
                                                                                                           Death within 30 minutes.       0.98      0.89      0.93       279
                                                                  Dizziness, naseau, fagitue, headache after 2-3 hours of exposure.       0.93      1.00      0.96        26
                                                      Headache and nausea after 1-2 hours of exposure.
Life threatening in 3 hours.       1.00      0.98      0.99        92
                                              Headache, nausea, and dizziness after 20 minutes of exposure.
Death within 1-2 hours.   

In [37]:
print(accuracy_score(y_test, knn_predictions))

0.9641478212906784


In [62]:
#confusion matrix
conf_matrix = confusion_matrix(y_test, knn_predictions)
conf_matrix

array([[ 60,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 249,   0,   0,   0,   0,   0,  30,   0,   0,   0,   0],
       [  0,   0,  26,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   2,  90,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 281,   1,   4,   0,   1,   0,   0,   0],
       [  0,   0,   0,   0,   0,  50,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  17,   0, 325,   0,   0,   0,   0,   0],
       [  2,   6,   0,   0,   0,   0,   0,  39,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 108,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 192,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 311,   2],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  17]],
      dtype=int64)

In [38]:
from sklearn.externals import joblib
joblib.dump(knn, "health_effect.pkl")

C:\Users\User\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning:

sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.



['health_effect.pkl']

In [39]:
mod2=joblib.load("health_effect.pkl")
X_test[0]

array([1.90000e+00, 7.17776e+05, 8.91300e+03])

In [40]:
mod2.predict([X_test[0]])

array(['Death within 30 minutes.'], dtype=object)

In [50]:
mod2.predict([[2.1,70050,34]])

array(['Death within 30 minutes.'], dtype=object)

In [67]:
y_proba = knn.predict_proba(X_test)
# print(y_test)
# print(y_proba[:,0])

from sklearn import metrics
fpr , tpr , thold = metrics.roc_curve(y_test,y_proba[:,0],pos_label='e')
print(fpr)
print(thold)

[0.         0.0275786  0.03309432 0.03419746 0.03474903 1.        ]
[2.         1.         0.71428571 0.57142857 0.28571429 0.        ]


C:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:808: UndefinedMetricWarning:

No positive samples in y_true, true positive value should be meaningless

